### ISSUE TITLE
Kobo Stylus does not work for converted epub files

### ISSUE THREAD

**Issue by andrefrsousa** [pgaskin/kepubify#66]
Hello,

The new Kobo Elipsa has support for a Stylus which allows note-taking during reading. But unfortunately, this feature does not work for converted epubs.

I find out a forum where this matter was discussed recently: https://www.mobileread.com/forums/showthread.php?t=337241&page=39

Any idea how to fix it using kepubify?

Thanks.

**Comment by pgaskin** [comment]
This is a limitation of the firmware rather than an issue with kepubify or the KEPUB format. For some reason, at least right now, Kobo has decided to intentionally restrict the markup feature to KEPUBs from the Kobo Store.

I've [created](https://www.mobileread.com/forums/showthread.php?p=4133912#post4133912) a patch which can remove this restriction on versions 4.28.17623, 4.28.17820, and likely future versions.

```yaml
Enable markup for sideloaded kepubs:
  - Enabled: yes
  - ReplaceBytes:
      Base: "KepubMarkupDelegate::isMarkupSupported(Volume const&)"
      Offset: 64
      FindInstBLX: {SymPLT: "Content::isSideLoaded() const"}
      ReplaceH: 4F F0 00 00
```

**Comment by jonwest** [comment]
As a heads up, this patch works to remove the restriction and you're able to annotate the files as you would expect, however when you switch pages, the annotations disappear.  If you click on "annotations", you're able to see a preview of your annotations, but if you click on them, it takes you back to the page where they are no longer visible.  

Could be why it's restricted?  Seems really strange either way.  Really appreciate you diving into this, though, and hopefully Kobo fixes this (and many other bugs) shortly!  Thank you!

**Comment by pgaskin** [comment]
Thanks for testing the patch (I don't have an Elipsa, so I can't do it myself)! Next time I look at the patches, I'll see if I can figure out where the other condition is so I can fix that one too, or determine why it was disabled.

**Comment by AveryMensch** [comment]
Just to chime in, I've been using this patch since it was posted on the forum and it's been working perfectly for me. All of my kepubs are converted on upload by the Kobo Touch Extended driver.

**Comment by pgaskin** [comment]
Updated (but untested) patch for 4.29.18730:

```yaml
Enable markup for sideloaded kepubs:
  - Enabled: yes
  - ReplaceBytes:
      Base: "KepubMarkupDelegate::isMarkupSupported(Volume const&)"
      Offset: 390
      FindInstBLX: {SymPLT: "Content::isSideLoaded() const"}
      ReplaceH: 4F F0 00 00
```
