### ISSUE TITLE
Custom CSS not working in web interface

### ISSUE THREAD

**Issue by blehn** [pgaskin/kepubify#92]
Trying to force left justification and can't seem to do it.

I tried the following rules:

```
p { text-align: left; }
* { text-align: left; }
p { text-align: left; ! important }
* { text-align: left; !important }
```

After importing the output file into the Android Kobo app, text is still full justified.

Additional notes:
- I think text alignment would be a good setting to offer (rather than using custom CSS) given that it's probably one of the most common user formatting preferences
- The UI makes it difficult to tell whether or not settings are being applied to the conversion.

**Comment by pgaskin** [comment]
- Your CSS has syntax errors. Try this:
  ```css
  *, p { text-align: left !important }
  ```

- It could also be more [specific](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity); try adding this if it still doesn't work:
  ```css
  html > body *, html > body p { text-align: left !important }
  ```

- Additional built-in options for CSS tweaks are out of scope for kepubify unless they directly relate to a kepub bug or feature.

- When you say it's hard to know if it's being applied, are you referring to knowing when the settings take effect, or something else?
